### PR TITLE
New Style and Logo

### PR DESCRIPTION
**Pull request by jmartin2939**
screenshot attached of proposed changes.
capture

Added temp display page for all recorded pastes, I intend to make this better in the near future, but as commie is to be considered "Beta", it's a Beta feature. 

Adjusted the layout to be more mobile friendly. 

Changed the logo to give it an edge.

added auto-changing date to the footer using javascript. 

I hope with future changes, Commie can be the best non-DB paste bin available.

### CODE REVIEW

**Comment by clawoflight** [comment]
To be honest, I prefer the looks of the current version.
This is subjective of course, but right now, it looks geeky and clean, while this looks rather cheap.

The feature additions look very nice though.

**Comment by jmartin2939** [comment]
understandable, it's a lot changes to take in, and most are preference. 

I'll back to drawing board and focus on things like mobile friendliness without compromising the current branding and style.

if changes to become regular, how do you guys feel about versioning?

**Comment by clawoflight** [comment]
I compared your screenshot and my server's version side-by-side.
Maybe this helps understand my point of view:
1. The bright blue and full-width bar at the top are, I think, what makes it look cheapest to me
2. I like the amount of left padding that the current version has, it 's more pleasant to look at. Try adding that back.
3. The logo is huge and attracts way more attention than the actual interface. It doesn't look bad, just too prominent.
4. It looks weird to have the reminder about the posts being public on a separate line like that. You could try either making it small and italic and add vertical padding, or have it flow below the button only if it would otherwise not fit. (Add a div around both, I guess)

I think that the awesome geeky flair of the original comes from a few things:
- white text on off-black
- monospace ASCII-art
- the very distraction-free, no-nonsense interface.

I hope that this feedback helps you in refining your redesign :)

**Comment by splitbrain** [comment]
I agree with @clawoflight on the design. I'm happy about PRs helping with mobile adjustments but wouldn't want to change the simple design to much.

About the features. I am not sure that I want a list of pastes. Even though all pastes are accessible without password they are pseudo secret as long as you don't know the URL. Adding a list defeats that. It might also make the pastebin more attractive for spam.

The code it self is also not up to be merged currently. There is a lot of unnecessary repetition in it and I input sanitation seems questionable (without having looked much into it).

I'm closing this for now. Feel free to open new, smaller PRs with single features/design fixes.

**Comment by jmartin2939** [comment]
closing this and applying feedback to future PRs. Thanks gentlemen.

**Pull request closed without merging**
